#!/usr/bin/env python3

# This file is part of the Python Learning of Class Object Constructor Attribute and method.

class Student:
    def __init__(self,name,id):
        self.name = name
        self.id = id

    # Method to display the student's name and ID
    def display(self):
        print("Name:",self.name,"ID:",self.id)

# Create an instance of the Student class
Student_1 = Student("Aadil", 101)  # Create an object of the Student class
Student_2 = Student("Zayan", 102)  # Create another object of the Student class

# Call the display method for each instance
Student_1.display()  # Output: Name: Aadil ID: 101
Student_2.display()  # Output: Name: Zayan ID: 102
